from cmu_graphics import *
from PIL import Image

app.width = 650
app.height = 650

#--code from makeNewImages.py 4/11 lecture--

#original images
app.ogStart = Image.open('pngs/start_bg.PNG')
app.ogScreen = Image.open('pngs/opening_screen.PNG')
app.ogButton = Image.open('pngs/start.PNG')
app.ogMapBG = Image.open('pngs/map_bg.PNG')
app.ogMap = Image.open('pngs/map.PNG')
app.ogServe = Image.open('pngs/serving_window.PNG')
app.ogTop = Image.open('pngs/top_bar.PNG')
app.ogSupplies = Image.open('pngs/supplies_w_tomato.PNG')
app.ogTrash = Image.open('pngs/trash.PNG')
app.ogSink = Image.open('pngs/sink.PNG')
app.ogTemp = Image.open('pngs/temp_character.PNG')
app.ogCut = Image.open('pngs/cutting_board.PNG')
app.ogKnife = Image.open('pngs/knife.PNG')
app.ogStove = Image.open('pngs/stove.PNG')
app.ogTopPlate = Image.open('pngs/plate_top_view.PNG')
app.ogSidePlate = Image.open('pngs/plate_side_view.PNG')
app.ogPan = Image.open('pngs/pan.PNG')
app.ogUp = Image.open('pngs/walking_up.PNG')
app.ogDown = Image.open('pngs/walking_down1.PNG')
app.ogLeft = Image.open('pngs/walking_left1.PNG')
app.ogRight = Image.open('pngs/walking_right1.PNG')
app.ogTickets = Image.open('pngs/tickets.PNG') 
app.ogBun = Image.open('pngs/bun.PNG')
app.ogRawPatty = Image.open('pngs/raw_patty.PNG')
app.ogPatty = Image.open('pngs/patty.PNG')
app.ogBurntPatty = Image.open('pngs/burnt_patty.PNG')
app.ogSlicedTomato = Image.open('pngs/sliced_tomato.PNG')
app.burgerSprites = Image.open('pngs/burger_possibilities.PNG')
app.ogEnd = Image.open('pngs/end_screen.PNG')
app.ogCoin = Image.open('pngs/coin.PNG')
app.ogMissing = Image.open('pngs/missing_star.PNG')
app.ogStar = Image.open('pngs/star.PNG')
app.ogHighlight = Image.open('pngs/highlighted.PNG')
app.ogInstruct1 = Image.open('pngs/instructions1.PNG')
app.ogContinue = Image.open('pngs/continueButton.PNG')
app.ogTutMap1 = Image.open('pngs/tutorial_map.PNG')
app.ogInstruct2 = Image.open('pngs/instructions2.PNG')
app.ogTutMap2 = Image.open('pngs/tutorial_map2.PNG')
app.ogReset = Image.open('pngs/resetButton.PNG')
app.ogInstruct3 = Image.open('pngs/instructions3.PNG')
app.ogTutMap3 = Image.open('pngs/tutorial_map3.PNG')
app.ogProfit = Image.open('pngs/profit_tracker.PNG')

#resized images
app.startBG = CMUImage(app.ogStart.resize((app.width, app.height)))
app.startScreen = CMUImage(app.ogScreen.resize((550, 550)))
app.startButton = CMUImage(app.ogButton.resize((512//3, 178//3)))
app.map = CMUImage(app.ogMap.resize((app.width, app.height)))
app.serveWindow = CMUImage(app.ogServe.resize((400//3, 600//3)))
app.topBar = CMUImage(app.ogTop.resize((app.width, 340//3)))
app.tutResize = app.ogSupplies.resize((1330//5, 340//5))
app.tutSupply = CMUImage(app.tutResize.crop((0, 0, 65, 70)))
app.supplies = CMUImage(app.ogSupplies.resize((1330//4, 340//4)))
app.trash = CMUImage(app.ogTrash.resize((296//3, 258//3)))
app.tutSink = CMUImage(app.ogSink.resize((550//5, 274//5)))
app.sink = CMUImage(app.ogSink.resize((550//3, 274//3)))
app.tempChar = CMUImage(app.ogTemp.resize((289//3, 478//3)))
app.tutTempChar = CMUImage(app.ogTemp.resize((289//5, 478//5)))
app.cuttingBoard = CMUImage(app.ogCut.resize((290//3, 225//3)))
app.knife = CMUImage(app.ogKnife.resize((128//3, 187//3)))
app.stove = CMUImage(app.ogStove.resize((270//3, 245//3)))
app.topPlate = CMUImage(app.ogTopPlate.resize((174//3, 167//3)))
app.sidePlate = CMUImage(app.ogSidePlate.resize((200//3, 85//3)))
app.pan = CMUImage(app.ogPan.resize((286//3, 315//3)))

app.tutUpSprite = app.ogUp.resize((1994//5, 536//5))
app.tutDownSprite = app.ogDown.resize((1897//5, 482//5))
app.tutLeftSprite = app.ogLeft.resize((1614//5, 480//5))
app.tutRightSprite = app.ogRight.resize((1614//5, 480//5))

app.upSprite = app.ogUp.resize((1994//3, 536//3))
app.downSprite = app.ogDown.resize((1897//3, 482//3))
app.leftSprite = app.ogLeft.resize((1614//3, 480//3))
app.rightSprite = app.ogRight.resize((1614//3, 480//3))

app.resizeTickets = app.ogTickets.resize((1300//3, 405//3))
app.resizeTutTicket = app.ogTickets.resize((1300//6, 405//6))
app.tutOrderBurger = CMUImage(app.resizeTutTicket.crop((140, 0, 215, 100)))
app.orderBurger = CMUImage(app.resizeTickets.crop((0, 0, 145, 160)))
app.orderTomatoBurg = CMUImage(app.resizeTickets.crop((145, 0, 280, 160)))
app.orderCheeseburger = CMUImage(app.resizeTickets.crop((280, 0, 425, 160)))
app.rawPatty = CMUImage(app.ogRawPatty.resize((85//3, 35//3)))
app.bun = CMUImage(app.ogBun.resize((135//3, 100//3))) #sliced bun
app.patty = CMUImage(app.ogPatty.resize((90//3, 35//3)))
app.burntPatty = CMUImage(app.ogBurntPatty.resize((85//3, 35//3)))
app.slicedTomato = CMUImage(app.ogSlicedTomato.resize((99//3, 55//3)))
app.resizeBurgerSprite = app.burgerSprites.resize((446//3, 578//3))
app.end = CMUImage(app.ogEnd.resize((915//3, 1200//3)))
app.coin = CMUImage(app.ogCoin.resize((100//2, 100//2)))
app.missingStar = CMUImage(app.ogMissing.resize((185//3, 185//3)))
app.star = CMUImage(app.ogStar.resize((185//3, 185//3)))
app.highlighted = CMUImage(app.ogHighlight.resize((335//3, 335//3)))
app.tutHighlight = CMUImage(app.ogHighlight.resize((335//5, 335//5)))
app.sinkHighlight = CMUImage(app.ogHighlight.resize((200, 335//3)))
app.windowHighlight = CMUImage(app.ogHighlight.resize((335//3, 220)))
app.instruct1 = CMUImage(app.ogInstruct1.resize((2048//3, 2048//3)))
app.continueButton = CMUImage(app.ogContinue.resize((525//4, 190//4)))
app.tutMap1 = CMUImage(app.ogTutMap1.resize((920//3, 590//3)))
app.instruct2 = CMUImage(app.ogInstruct2.resize((2048//3, 2048//3)))
app.tutMap2 = CMUImage(app.ogTutMap2.resize((870//3, 545//3)))
app.reset = CMUImage(app.ogReset.resize((515//4, 190//4)))
app.instruct3 = CMUImage(app.ogInstruct3.resize((2048//3, 2048//3)))
app.tutMap3 = CMUImage(app.ogTutMap3.resize((1070//3, 565//3)))
app.profit = CMUImage(app.ogProfit.resize((345//5, 124//5)))

#correct orders:
app.hamburger = CMUImage(app.resizeBurgerSprite.crop((0, 0, 50, 50)))
app.cheeseBurger = CMUImage(app.resizeBurgerSprite.crop((50, 0, 100, 40)))
app.tomatoBurg = CMUImage(app.resizeBurgerSprite.crop((100, 40, 150, 80)))
app.cheeseBun = CMUImage(app.resizeBurgerSprite.crop((100, 0, 150, 40)))
app.tomatoBun = CMUImage(app.resizeBurgerSprite.crop((5, 80, 50, 110)))
app.pattyTomato = CMUImage(app.resizeBurgerSprite.crop((55, 80, 100, 110)))
app.cheeseTomato = CMUImage(app.resizeBurgerSprite.crop((55, 120, 100, 155)))

#incorrect orders (bottom-->top):
app.tomatoCheesePatty = CMUImage(app.resizeBurgerSprite.crop((0, 45, 50, 85)))
app.pattyTomatoCheese = CMUImage(app.resizeBurgerSprite.crop((50, 45, 100, 85)))
app.cheesePatty = CMUImage(app.resizeBurgerSprite.crop((100, 75, 150, 105)))
app.tomatoCheese = CMUImage(app.resizeBurgerSprite.crop((10, 120, 50, 160)))
app.tomatoPatty = CMUImage(app.resizeBurgerSprite.crop((105, 120, 150, 155)))
app.tomatoPattyCheese = CMUImage(app.resizeBurgerSprite.crop((10, 155, 
                                                              50, 205)))
app.cheesePattyTomato = CMUImage(app.resizeBurgerSprite.crop((60, 155, 
                                                              110, 205)))
app.cheeseTomatoPatty = CMUImage(app.resizeBurgerSprite.crop((105, 155, 
                                                              160, 205)))